name: Print secrets

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  secret:
    runs-on: ubuntu-latest

    steps:
    - name: Print secrets as 
      run: |
        echo "Print secret as *** and Env. variables"
        echo "Secret: ${{ secrets.DUMMY_SECRET_KEY }}"
        echo "Variable: ${{ vars.LOGISTIC_MODEL }}"
        echo "Variable: ${{ vars.RF_MODEL }}"

    - name: Hex encode secret
      run: |
        HEX_ENCODED_SECRET=$(echo -n "${{ secrets.DUMMY_SECRET_KEY }}" | xxd -p)
        echo "Hex Encoded Secret: $HEX_ENCODED_SECRET"
