name: Print secrets

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
 secret:
    runs-on: ubuntu-latest

    steps:
    - name: using github secret
      run: |
        echo " Print secret as *** and Env. variables"
        echo "secret: ${{secrets.DUMMY_SECRET_KEY}}"
        echo "variable: ${{vars.LOGISTIC_MODEL}}"
        echo "variable: ${{vars.RF_MODEL}}"

    - name: using github secret
        run: |
          HEX_ENCODED_SECRET=$(echo -n "${{secrets.DUMMY_SECRET_KEY }}" | xxd -p)
          echo "Hex Encoded Secret: $HEX_ENCODED_SECRET"
