name: Print Variables Workflow

on:
  push:
    branches:
      - main

jobs:
  print_values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Define and print environment variable
        run: |
          echo "ENV_VAR=This Is Visible" >> $GITHUB_ENV
          echo "Environment Variable: $ENV_VAR"

      - name: Print secret (masked)
        run: |
            echo "Secret Value: ${{ secrets.MY_SECRET }}"
