name: Hex Encode and Decode Secret

on:
  push:
    branches:
      - main

jobs:
  hex-encode-decode:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print original secret
      run: |
        echo "Original Secret (masked as ***): ${{ secrets.DUMMY_SECRET_KEY }}"

    - name: Hex encode secret
      id: encode
      run: |
        HEX_ENCODED_SECRET=$(echo -n "${{ secrets.DUMMY_SECRET_KEY }}" | xxd -p)
        echo "Hex Encoded Secret: $HEX_ENCODED_SECRET"
        echo "HEX_ENCODED_SECRET=$HEX_ENCODED_SECRET" >> $GITHUB_ENV

    - name: Decode hex-encoded secret
      id: decode
      run: |
        echo "$HEX_ENCODED_SECRET" | xxd -r -p
      env:
        HEX_ENCODED_SECRET: ${{ env.HEX_ENCODED_SECRET }}
